directory: terraform

framework:
  - terraform

output: junitxml
output-file-path: results.xml

soft-fail: true
quiet: false

evaluate-variables: true
external-modules-download-path: .external_modules

skip-path:
  - "**/.terraform/**"
  - "**/.external_modules/**"

# skip-check:
#   - CKV_AWS_2
#   - CKV_AWS_18