sonar.projectKey=educloud
sonar.projectName=EduCloud
sonar.projectVersion=1.0

sonar.sources=frontend/src,terraform

sonar.exclusions=frontend/build/**,frontend/public/**,**/*.tfstate,**/*.tfstate.backup,**/node_modules/**,**/*.min.js

sonar.sourceEncoding=UTF-8
# sonar.host.url se inyecta desde variable de entorno SONAR_HOST_URL en CI
# o desde el comando al correr localmente