sonar.projectKey=educloud
sonar.projectName=EduCloud
sonar.projectVersion=1.0

# Analizamos frontend (React) y terraform por separado con comas
sonar.sources=frontend/src,terraform

# Excluimos build generado, archivos de estado de terraform y estáticos
sonar.exclusions=frontend/build/**,frontend/public/**,**/*.tfstate,**/*.tfstate.backup,**/node_modules/**,**/*.min.js

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000