name: Analisis SonarQube

on:
  push:
    branches: [main, dev, prod]
  pull_request:
    branches: [main, dev, prod]

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias del frontend
        working-directory: frontend
        run: npm install

      - name: Ejecutar analisis SonarQube
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_SCANNER_OPTS: "-Dsonar.scanner.skipJreProvisioning=true -Dhttp.requestHeader.ngrok-skip-browser-warning=true"

      - name: Verificar Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}